build:
	 g++ socksrv_thpool_aff.cpp -o socksrv_thpool_aff
	 g++ sockclient.cpp -o sockclient

debug:
	 g++ -g socksrv_thpool_aff.cpp -o socksrv_thpool_aff
	 g++ -g sockclient.cpp -o sockclient

clean:
	rm socksrv_thpool_aff sockclient
